apiVersion: v1
kind: Service
metadata:
  name: qrcode-nodeport
  namespace: qrcode
spec:
  type: NodePort
  selector:
    app: qrcode
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30085